### ISSUE TITLE
🐛 ~ `Error while loading rule 'functional/functional-parameters': Object.fromEntries is not a function`

### ISSUE THREAD

**Issue by rivy** [jonaskello/eslint-plugin-functional#172] opened 2021-01-01 05:04 UTC
Platform: MacOS, Ubuntu, and Windows
NodeJS: v10.23.0
ESLint: v7.16.0

From working `v3.1.0`, `v3.2.0` now causes this error when running `npx eslint .`:

```text
ESLint: 7.16.0

TypeError: Error while loading rule 'functional/functional-parameters': Object.fromEntries is not a function
Occurred while linting C:\Users\Roy\OneDrive\Projects\js\js.os-paths\repo\eg\show-paths.js
    at create (C:\Users\Roy\OneDrive\Projects\js\js.os-paths\repo\node_modules\eslint-plugin-functional\lib\index.js:498:48)
    at Object.create (C:\Users\Roy\OneDrive\Projects\js\js.os-paths\repo\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\RuleCreator.js:13:24)
    at createRuleListeners (C:\Users\Roy\OneDrive\Projects\js\js.os-paths\repo\node_modules\eslint\lib\linter\linter.js:761:21)
    at Object.keys.forEach.ruleId (C:\Users\Roy\OneDrive\Projects\js\js.os-paths\repo\node_modules\eslint\lib\linter\linter.js:931:31)
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\Roy\OneDrive\Projects\js\js.os-paths\repo\node_modules\eslint\lib\linter\linter.js:876:34)
    at Linter._verifyWithoutProcessors (C:\Users\Roy\OneDrive\Projects\js\js.os-paths\repo\node_modules\eslint\lib\linter\linter.js:1173:31)
    at Linter._verifyWithoutProcessors (C:\Users\Roy\OneDrive\Projects\js\js.os-paths\repo\node_modules\eslint-plugin-eslint-comments\lib\utils\patch.js:181:42)
    at Linter._verifyWithConfigArray (C:\Users\Roy\OneDrive\Projects\js\js.os-paths\repo\node_modules\eslint\lib\linter\linter.js:1271:21)
    at Linter.verify (C:\Users\Roy\OneDrive\Projects\js\js.os-paths\repo\node_modules\eslint\lib\linter\linter.js:1226:25)
```

Using either NodeJS v12.20.0+ or holding eslint-plugin-functional to "<3.2.0", `npx eslint .` completes without error.

[GitHub CI](https://github.com/rivy/js.os-paths/actions/runs/454955603) was noted to start failing on [MacOS](https://github.com/rivy/js.os-paths/runs/1631230365?check_suite_focus=true), [Ubuntu](https://github.com/rivy/js.os-paths/runs/1631230397?check_suite_focus=true), and [Windows](https://github.com/rivy/js.os-paths/runs/1631230431?check_suite_focus=true) NodeJS-v10 earlier today.

**Comment by RebeccaStevens** [comment] 2021-01-01 05:21
Ahh, damn. There was a weird problem when I made the release. I should have tested it afterwards.
I'll mark that release and broken and try and get a new fixed release out soon.

**Comment by rivy** [comment] 2021-01-01 05:25
I enabled all rules, then sequentially disabled them; and, it's seems all of the rules are affected by the same issue.

**Comment by RebeccaStevens** [comment] 2021-01-01 05:44
I just looked at the diff between the two releases and it seems that the problem is just that the polyfills for older versions of node were not included. I suspect v3.2 should run fine on node 14 and up.

**Comment by rivy** [comment] 2021-01-01 05:48
It ran fine on NodeJS-v12+.

**Comment by RebeccaStevens** [comment] 2021-01-01 07:28
Should be fix now in v3.2.1

**Comment by RebeccaStevens** [comment] 2021-01-01 07:33
Closing this now. Comment here if it doesn't seem to be fixed.

**Closed by RebeccaStevens** 2021-01-01 07:33 UTC
Labels: Priority: Critical, Resolution: Done/Fixed, Type: Bug

**Comment by rivy** [comment] 2021-01-02 00:01
Looks good, local and CI passing.
Thanks for the attention!
