### ISSUE TITLE
[prefer-readonly-type] - Don't report if type is wrapped with ReadOnly utility

### ISSUE THREAD

**Issue by avalanche1** [jonaskello/eslint-plugin-functional#96] opened 2020-03-26 09:54 UTC
To my knowledge, logically these two are the same:
```ts
type Row = {
 readonly name: string;
 readonly code: string;
}

type Row = Readonly<{
  name: string;
  code: string;
}>
```
The rule reports on the second case. I think it shouldnt.

**Comment by RebeccaStevens** [comment] 2020-03-27 05:18
Yes, you're correct. We don't current have support for this.

Duplicate of #51

**Closed by RebeccaStevens** 2020-03-27 05:18 UTC
